Entertainment/urls.py
# create urls.py in the directory of the Entertainment app

# import path to map a URL to a specific view function in Django
# import include to use other URL patterns from other modules (apps)
from django.urls import path

# import views which contain the functions or classes responsible for handling HTTP requests
# and returning appropriate responses, rendering web pages.
from Entertainment import views

#############################################################################################
#############################################################################################

# add an app_name to set the application namespace
app_name = 'Entertainment'

# under urlpatterns, paste the code that references the functions in views.py
urlpatterns = [
    # set a path for the home view of Entertainment
    path('', views.index_en, name='index_en'),   
    # set a path for the detail view
    path('<str:category_name>/<int:question_id>/detail/', views.detail, name='en_detail'),
    # set a path for the selection view
    path('<str:category_name>/<int:question_id>/selection/', views.selection, name='selection'),    
    # set a path for the results view
    path('<str:category_name>results/', views.results, name='results'),
    # set a path for the start a new quiz view
    path('Entertainment/try_new_quiz/', views.try_new_quiz, name='try_new_quiz')    
]

QuizMe/urls.py
# import admin to make the Django admin functionality available for use in your Django project
# admin allows administrators to easily add, edit, and delete records from the database
from django.contrib import admin

# import path function to define a URL pattern for the paths to apps 
# alter import to add 'include' to include additional URL patterns within the modules(apps)
from django.urls import path, include

#############################################################################################
#############################################################################################

'''
Add paths for the modules in QuizMe.
'''
# add path for admin
# add paths for the apps created in QuizMe
# edu has index.html so leave path open for it to render when server starts
urlpatterns = [
    path('admin/', admin.site.urls),      
    path('', include("Education.urls")),
    path('user_auth/', include("user_auth.urls")),
    path('Entertainment/', include("Entertainment.urls")),
    path('General_Knowledge/', include("General_Knowledge.urls"))
]

Entertainment/views.py
# import render to render an HTML template with a given context and return an HttpResponse object
# use get_object_or_404 in views.py to render a HTTP 404 error if a question with the requested ID doesn’t exist
from django.shortcuts import get_object_or_404, render

# Import the login required decorator to prevent unaouthorised access to cetrain views.
from django.contrib.auth.decorators import login_required

# imported HttpResponseRedirect 
from django.http import HttpResponseRedirect

# imported reverse
from django.urls import reverse

# import functions from utils.py called in views
from .utils import get_json_categories, get_next_question_id, get_category_names, category_objects

# import all models
from Entertainment.models import *

# import apps to dynamically fetch a model in detail() view
from django.apps import apps

# import Http404 to raise an error message if a model is not located in detail view
from django.http import Http404

# import logging for debugging
import logging

# import ast safely evaluate strings containing Python literal structures e.g.strings, lists, dicts
# use to convert str into list
import ast 

#######################################################################################
#######################################################################################

# Create your views here.
'''
Create a view for the home page of Entertainment quizzes.
'''
# display the category of the  quiz
# https://www.youtube.com/watch?v=sgEhb50YSTE
# get json reponse for trivia categories from open trivia db
# index category from the dictionary id
def index_en(request):
    """
    This function represents the homepage of Entertainment quizzes.
    It displays a list of categories of quizzes and the first question of each category.
    If a user prematurely leaves a quiz and does not use the exit button,
    the result and session data of the current quiz are deleted.

    :param request: The HTTP request object (optional, if needed).
    :type request: HttpRequest
    :return: The en_quiz template.
    :rtype: HTTPResponse
    """
    # if a user prematurely leaves a quiz & does not use the exit button,
    # - delete the result & session data of the current quiz 
    # - this is done for all the templates the navbar displays
    if 'quiz_result' in request.session:
        del request.session['quiz_result']

    # call the categories function & save its response in an assigned variable - NameError if you don't assign it
    response = get_json_categories()

    # call the function to return the chosen categories to present a quiz for on the homepage
    category_names = get_category_names(response)

    # iterate over the list of category_names to return the context for each subcategory in  app
    for category_name in category_names:
        # call the function to retrieve the objects from the django database - viewable on admin site
        question_selection =  category_objects(request, category_name)           

        # retrieve question_selection_pks from the session (from utils.category_objects)
        # because the 1st pk needs to be indexed for the 1st question rendered
        # question_selection.first().id chose the 1st question numerically in the database, not the 1st from the randomised list
        question_selection_pks = request.session['question_selection_ids']        
        print(f"index_edu=question_selection_ids in session:{question_selection_pks}") ##     

        # the response is the dictionary for trivia categories
        # pass all the context variables into a single dictionary to render in the template correctly
        context = {'category_names': category_names,
                   'question_selection': question_selection,
                   'first_question_id': question_selection_pks[0]
                   }            
        print(f"context:{context}") ##

        # render the context to the homepage of Entertainment
        return render(request, 'entertainment/en_quiz.html', context) 

# write a view for the quiz question, incl the argument question_id
# question_id is the specific identifier passed in the URL when accessing this view
# it uniquely identifies and retrieves the specific question to display
# Django automatically adds an id field as the primary key for each model (i.e. question.id)
# display the question text 
# render an HTTP 404 error if a question with the requested ID doesn’t exist
def detail(request, category_name, question_id):
    """
    This function retrieves a question object from the database based on the question_id passed in the URL.
    It also retrieves the list of choices for the question and converts the choices text field into a list of dictionaries.
    The function passes all the context variables into a single dictionary to render in the template correctly.

    :param request: The HTTP request object (optional, if needed).
    :type request: HttpRequest
    :param category_name: The name of the category.
    :type category_name: str
    :param question_id: The ID of the question.
    :type question_id: int
    :return: The detail template.
    :rtype: HTTPResponse
    """
    # retrieve the list of categories from the open trivia database
    response = get_json_categories()

    # retrieve the list of category names from the response
    category_names = get_category_names(response)

    # check if the category name is in the list of category names
    if category_name in category_names:
        # use the category name selected on edu_quiz.html to determine the model to get questions from
        # replace spaces and '&' in the event category names have spaces to create a valid model name
        model_name = category_name.replace(" ", "_").replace("&", "and")
        print(f"Model Name: {model_name}")  # noqa: D105

        # use a try-except block to find a model that matches the category name
        # use use globals() instead of apps module to access the global namespace since the the model name was modified when replacing '&'
        # (apps still worked when it was only replacing " ")
        # - dynamically: instead of explicitly specifying a fixed model in the code, generate or determine the model to use at runtime based on certain conditions/data
        try:
            model = globals()[model_name]  # noqa: D105

        # raise an error if the model is not found
        except LookupError:
            raise Http404("Cannot locate the model for the selected category.")  # noqa: D105

        # get the question object associated with a specific question_id in the database
        question = get_object_or_404(model, pk=question_id)  # noqa: D105
        print(f"\n\nquestion:{question}")
        print(f"correct_answer:{question.correct_answer}")

        # use the helper function literal_eval of the ast module to convert the str representation of the choices list
        # - in the textfield of the category model into a list
        # https://python.readthedocs.io/en/latest/library/ast.html#ast.literal_eval
        # note: ast.literal_eval is safer than eval. it only evaluates literals & not arbitrary expressions,
        # - reducing the risk of code injection
        # use in template to iterate over the list of choices dictionaries and access the values for the 'choice' key
        convert_choices_textfield_into_list = ast.literal_eval(question.choices)  # noqa: D105

        # render the edu_detail template & pass the 10 questions, their ids & category as context
        context = {
            "question": question,
            "choices": convert_choices_textfield_into_list,
            "category_name": category_name,
        }
        print(f"context:{context}")  # noqa: D105

        return render(request, "entertainment/en_detail.html", context)


# create a view that displays the quiz result 
def results(request, category_name: str):
    """
    This function retrieves the quiz result from the session and renders the result template.

    :param request: The HTTP request object (optional, if needed).
    :type request: HttpRequest
    :param category_name: The name of the category.
    :type category_name: str
    :return: The result template.
    :rtype: HTTPResponse
    """
    # get the quiz result for the session
    result = request.session.get('quiz_result')

    # render the result template
    # pass the quiz result for the session as a context variable
    context = {'result': result,
               'category_name': category_name
               }
    return render(request, 'entertainment/en_result.html', context)


# write a view to answer a question, incl the argument category_name & question_id
# it handles the submitted data
def selection(request, category_name, question_id):
    """
    Handles the submitted data for a question in a quiz.

    :param request: The HTTP request object (optional, if needed).
    :type request: HttpRequest
    :param category_name: The name of the category.
    :type category_name: str
    :param question_id: The ID of the question.
    :type question_id: int
    :return: The detail template.
    :rtype: HTTPResponse
    """
    # retrieve the list of categories from the open trivia database
    response = get_json_categories()

    # retrieve the list of category names from the response
    category_names = get_category_names(response)

    # check if the category_name is in the list of category_names then locate its model
    # use globals module instead of apps to access the global namespace for models
    # - since a model name was altered from its original category_name to create a valid model with 'and'
    if category_name in category_names:
        model_name = category_name.replace(" ", "_").replace("&", "and")
        model = globals()[model_name]  # noqa: D105

        # get the question object associated with a specific question_id in the database
        question = get_object_or_404(model, pk=question_id)  # noqa: D105

Entertainment/templates/entertainment/en_detail.html
{% extends "index.html" %}
{% load static %}
<!DOCTYPE html>
<html lang = "en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
	integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">		
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
	<!--NOTE: the url to stylesheet & palcement of '/'; this renders external css correctly-->
	<link href="{% static 'CSS/StyleSheet_edu.css' %}" rel = "stylesheet" type = "text/css"> 
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title of the webpage -->
    <title>{% block title %}Entertainment Detail{% endblock %}</title>	
</head>    

<body>
	{% block content %}     
	    <section>
            <div class= row> 
                <!-- The exit quiz button with a tool tip.-->                   
                <div class= "col-md-6 d-flex justify-content-center pt-3 pe-10 me-0 mb-6">
                    <!-- use tooltips to display a message when hovering over the exit button for a quiz
                     https://getbootstrap.com/docs/5.0/components/tooltips/#examples-->
                    <a class="btn btn-outline-light" 
                    id="en_detail_btn" style="font-size: larger;"
                    href="{% url 'Entertainment:try_new_quiz' %}"
                    data-bs-toggle="tooltip" data-bs-placement="right" 
                    title="Warning: Leaving the quiz will cause you to lose the data submitted.">
                        Exit
                    </a>
                </div>
            </div>

            <div class="container-fluid text-center">
                <div class="row my-0 align-items-center justify-content-center">			
                    <div class = "col d-flex justify-content-center">
                        <div class="card en_p" style="width: 40rem;">		
                            <div class="card-body" id="no-underline">
                                <!--add a margin below the card-title -->
                                <h1 class="card-title mb-4"><i>{{ category_name }} quiz!</i></h1>		

                                    <!--show a form for each question in the quiz -->
                                    <!--the post method was used to send data to the server-->
                                    <!--the url in the action attribute was used to send data to the server-->
                                    <form action="{% url 'Entertainment:selection' category_name=category_name question_id=question.id %}" method="POST">
                                        <!--add the csrf_token to all post forms targeted at internal urls to protect against Cross Site Forgery-->
                                        {% csrf_token %}

                                        <!--The template system uses dot-lookup syntax to access variable attributes.-->
                                        <!-- Django does a dictionary lookup on the object question.-->
                                        <!--Failing that, it tries an attribute lookup – which works, in this case. -->
                                        <!--If attribute lookup has failed, it would’ve tried a list-index lookup.-->
                                        <!--check if there are question objects passed as context-->                    
                                        {% if question %}

                                                <!--display the question text by accessing its question attribute -->
                                                <!--add a margin below the question -->
                                                <h3 class="mb-4"> {{ question.question }} </h3> 

                                                <!--display error message if user did not select a choice before submitting-->
                                                {% if error_message %}
	    							                <p><strong>{{error_message}}</strong></p>
	    							            {% endif %}

                                                <!--group related elements in a form with fieldset-->
                                                <fieldset>   
                                                    <legend></legend>                                                                                            
                                                    <!--iterate over the choices attribute to add a radio button for each choice
                                                     associated with a specific question in the database-->
                                                    {% for choice in choices %}
                                                        <!--Radio buttons. Each choice that is associated with that particular question is
                                                        then displayed using a radio button in a form.-->
                                                        <!--The name of each radio button is choice-->
                                                        <!--selected value for each question will be sent to the server-->  
                                                        <!-- uniquely identify the radio button within the form-->
                                                        <!--the value attribute is the identifier for the user's choice associated with the question-->                                                                                              
                                                        <input type="radio" name="choice" 
                                                        id="choice{{forloop.counter}}" value="{{ choice.id }}" />                        
                                                        <!-- access the value associated with the 'choice' key in the question.choices dictionary-->
                                                        <label for="choice{{ forloop.counter }}">
                                                            {{ choice.choice }} 
                                                        </label>                                                                                                                                                                                                
                                                        <br/><br/>
                                                    {% endfor %}                                                                                                                                                                            
                                                    
                                                    <!-- a button that allows the user to submit their choice-->
                                                    <!--when a user selects one of the radio buttons and submits the form,
                                                         it’ll POST the data “choice=id” where id is the ID of the selected choice-->
                                                    <!--use margins to allow space above-under the button-->
                                                    <!-- use btn class so that the hover styles from the id will work-->                                                
                                                    <input type="Submit" value="Save" class="btn btn-outline-light" id="en_detail_btn"/>                                                                                                
                                                </fieldset>    

                                        <!--display error message if there are no questions-->                                                                                        
                                        {% else %}
                                            <p><strong>{{ error_message }}</strong></p>
                                        {% endif %}
                                            
                                    </form>                                                                

                            </div>	
                        </div>	
                    </div>
                </div>	                
            </div>
        </section>
	{% endblock %}
</body>
</html>

Entertainment/templates/entertainment/en_quiz.html
{% extends "index.html" %}
{% load static %}
<!DOCTYPE html>
<html lang = "en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
	integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">		
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
	<!--NOTE: the url to stylesheet & palcement of '/'; this renders external css correctly-->
	<link href="{% static 'CSS/StyleSheet_edu.css' %}" rel = "stylesheet" type = "text/css"> 
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Entertainment Quiz{% endblock %}</title>	
</head>    

<body>
	{% block content %}        
	    <section style="padding-left: 10pt;">     
            <div class = "row">
                <!--use the text-center class because text-align: center; in .category_heading did not work-->		
                <!-- set padding above & below the heading -->		
                <!--add a margin above the heading -->
                <div class = "col-md-12 text-center py-4 mt-4">
                    <!-- show a heading for the categories in Entertainment-->                    
                    <header>
                        <h1 id="en_heading"><span>Entertainment Quiz Categories</span></h1>
                    </header>                    
                </div>
            </div>     
            
            <!-- describe the Entertainment category -->
            <div class = "row">
                <div class = "col-md-12 text-center">
                    <p class="en_p" style="font-size: 20px;"><i>
                        Calling all music enthusiasts, film buffs, and video game lovers! Get ready to test your knowledge across the vast and thrilling realm of entertainment with this epic quiz extravaganza. We've got three exciting subcategories brimming with 10 random questions each, guaranteed to challenge and entertain you.
                    </i></p>
                </div>            
            </div>             
        </section>

        <section>
            <!--check if there are category names -->            
            <!-- list the categories-->
            {% if category_names %}  
                {% for category_name in category_names %}
                    <!--check if there are 10 questions for the category -->
                    {% if question_selection %}
                        
                        <!-- set padding above & below each subcategory -->		
                        <div class = "row py-3">
                            <!--an image button for the category -->  
                            <!--Add the d-flex and justify-content-center classes to the column. 
							This will make the column a flex container and center its contents horizontally--> 
                            <!-- vertically center the content with align-items-center--> 
                            <div class = "col-md-6 d-flex justify-content-center align-items-center">
                                <!--let the image adapt to viewport width- fluid layout expands to fill the available space -->                                                    
                                <div class="container-fluid">
                                    
                                    <!--Film category-->
                                    {% if category_name == "Film" %}
                                        <!-- call the url for the detail view of the first object in the question_selection queryset -->                    
                                        <!--alter the url to include the app_name=Entertainment 
                                        because namespaces are used to differentiate views between apps & create a url with the template tag-->
                                        <!-- pass parameters as keyword arguments from detail view without spaces or commas 
                                        generate links with the appropriate category_name. 
                                        the category_name is extracted from the selected_category object in utils.get_category_names-->
                                        <!-- display the name of the category as the button that takes you to the quiz -->
                                        <a href = "{% url 'Entertainment:en_detail' category_name=category_name question_id=first_question_id %}" class="btn">                                                 

                                            <img src ="{% static 'assets/film.jpg' %}" 
                                                alt = "Film" 
                                                class = "en_subcategory_image">
                                                
                                            <div class="subcategory_overlay">
                                                <div class="en_subcategory_text">
                                                    {{ category_name }}
                                                </div>
                                            </div>

                                        </a>    

                                    <!--Music category-->
                                    {% elif category_name == "Music" %}
                                        <a href = "{% url 'Entertainment:en_detail' category_name=category_name question_id=first_question_id %}" class="btn">                                                 

                                            <img src ="{% static 'assets/music.jpg' %}" 
                                            alt = "Music" 
                                            class = "en_subcategory_image">

                                            <div class="subcategory_overlay">
                                                <div class="en_subcategory_text">
                                                    {{ category_name }}
                                                </div>
                                            </div>
                                            
                                        </a>  

                                    <!--Video Games category-->
                                    {% elif category_name == "Video Games" %}
                                        <!-- call the url for the detail view of the first object in the question_selection queryset -->                    
                                        <!--alter the url to include the app_name=Entertainment 
                                        because namespaces are used to differentiate views between apps & create a url with the template tag-->
                                        <!-- pass parameters as keyword arguments from detail view without spaces or commas 
                                        generate links with the appropriate category_name. 
                                        the category_name is extracted from the selected_category object in utils.get_category_names-->
                                        <!-- display the name of the category as the button that takes you to the quiz -->
                                        <a href = "{% url 'Entertainment:en_detail' category_name=category_name question_id=first_question_id %}" class="btn">                                                 

                                            <img src ="{% static 'assets/videogames.jpg' %}" 
                                                alt = "Video Games" 
                                                class = "en_subcategory_image">
                                                
                                            <div class="subcategory_overlay">
                                                <div class="en_subcategory_text">
                                                    {{ category_name }}
                                                </div>
                                            </div>

                                        </a> 

                                    {% endif %} 
                                    
                                </div>
                            </div>
                            
                            <div class = "col-md-6">
                                <!--a description for the Film category -->                    
                                {% if category_name == "Film" %}
                                    <p class="en_p">Dive into the Silver Screen: A Celebration of Film!
                                        Film, the magic of moving pictures, has captivated audiences for over a century. This category delves into the captivating world of cinema, exploring its various elements, genres, and iconic moments.
                                    </p>

                                <!--a description for the Music category -->                    
                                {% elif category_name == "Music" %}
                                    <p class="en_p">The Universal Language: A Journey Through Music
                                        Music, the language that transcends borders and speaks to the soul, has been a fundamental part of human culture for millennia. This category dives into the world of music, exploring its diverse genres, foundational elements, and the profound impact it has on our lives.
                                    </p>

                                <!--a description for the Video Games category -->                    
                                {% elif category_name == "Video Games" %}
                                    <p class="en_p">Power Up! Exploring the Thrilling World of Video Games
                                        Video games, once a niche hobby, have exploded into a global phenomenon. This category delves into the captivating world of gaming, exploring its diverse genres, the technology that brings them to life, and the unique experiences they offer.
                                    </p>
                                
                                {% endif %} 
                            </div>
                        </div>                                                         
                        
                    {% endif %}                
                {% endfor %}

            <!--display an error message if a quiz was not found for a category -->
            {% else %}
                <p>No quizzes are available.</p>
            {% endif %}

        </section>
	{% endblock %}
    
</body>
</html>