Education/urls.py
# create urls.py in the directory of the education app

# import path to map a URL to a specific view function in Django
# import include to use other URL patterns from other modules (apps)
from django.urls import path, include

# import views which contain the functions or classes responsible for handling HTTP requests
# and returning appropriate responses, rendering web pages.
from . import views

#############################################################################################
#############################################################################################

# add an app_name to set the application namespace
app_name = 'Education'

# under urlpatterns, paste the code that references the functions in views.py
urlpatterns = [
    # set a path for the home page of QuizMe
    path('', views.index, name='index'),   
    # set a path for the home view of education
    path('Education/', views.index_edu, name='index_edu'),   
    # set a path for the detail view
    path('<str:category_name>/<int:question_id>/detail/', views.detail, name='edu_detail'),
    # set a path for the selection view
    path('<str:category_name>/<int:question_id>/selection/', views.selection, name='selection'),    
    # set a path for the results view
    path('<str:category_name>/results/', views.results, name='results'),
    # set a path for the start a new quiz view
    path('Education/try_new_quiz/', views.try_new_quiz, name='try_new_quiz')
]

Entertainment/urls.py
# create urls.py in the directory of the Entertainment app

# import path to map a URL to a specific view function in Django
# import include to use other URL patterns from other modules (apps)
from django.urls import path

# import views which contain the functions or classes responsible for handling HTTP requests
# and returning appropriate responses, rendering web pages.
from Entertainment import views

#############################################################################################
#############################################################################################

# add an app_name to set the application namespace
app_name = 'Entertainment'

# under urlpatterns, paste the code that references the functions in views.py
urlpatterns = [
    # set a path for the home view of Entertainment
    path('', views.index_en, name='index_en'),   
    # set a path for the detail view
    path('<str:category_name>/<int:question_id>/detail/', views.detail, name='en_detail'),
    # set a path for the selection view
    path('<str:category_name>/<int:question_id>/selection/', views.selection, name='selection'),    
    # set a path for the results view
    path('<str:category_name>results/', views.results, name='results'),
    # set a path for the start a new quiz view
    path('Entertainment/try_new_quiz/', views.try_new_quiz, name='try_new_quiz')    
]

General_Knowledge/urls.py
# create urls.py in the directory of the education app

# import path to map a URL to a specific view function in Django
# import include to use other URL patterns from other modules (apps)
from django.urls import path, include

# import views which contain the functions or classes responsible for handling HTTP requests
# and returning appropriate responses, rendering web pages.
from . import views

#############################################################################################
#############################################################################################

# add an app_name to set the application namespace
app_name = 'General_Knowledge'

# under urlpatterns, paste the code that references the functions in views.py
urlpatterns = [
    # set a path for the home view of General Knowledge
    path('General_Knowledge/', views.index_gen, name='index_gen'),   
    # set a path for the detail view
    path('<str:category_name>/<int:question_id>/detail/', views.detail, name='gen_detail'),
    # set a path for the selection view
    path('<str:category_name>/<int:question_id>/selection/', views.selection, name='selection'),    
    # set a path for the results view
    path('<str:category_name>results/', views.results, name='results'),
    # set a path for the start a new quiz view
    path('General_Knowledge/try_new_quiz/', views.try_new_quiz, name='try_new_quiz')    
]

QuizMe/urls.py
# import admin to make the Django admin functionality available for use in your Django project
# admin allows administrators to easily add, edit, and delete records from the database
from django.contrib import admin

# import path function to define a URL pattern for the paths to apps 
# alter import to add 'include' to include additional URL patterns within the modules(apps)
from django.urls import path, include

#############################################################################################
#############################################################################################

'''
Add paths for the modules in QuizMe.
'''
# add path for admin
# add paths for the apps created in QuizMe
# edu has index.html so leave path open for it to render when server starts
urlpatterns = [
    path('admin/', admin.site.urls),      
    path('', include("Education.urls")),
    path('user_auth/', include("user_auth.urls")),
    path('Entertainment/', include("Entertainment.urls")),
    path('General_Knowledge/', include("General_Knowledge.urls"))
]

user_auth/urls.py
"""
This file contains the URL patterns for the user authentication app.
"""
from django.urls import path
from user_auth import views

app_name = 'user_auth'
urlpatterns = [
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.user_register, name="register"),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('authenticate_user/show_user', views.show_user, name='show_user'),  # The url path to user page.

]

Education/views.py
# import render to render an HTML template with a given context and return an HttpResponse object
# use get_object_or_404 in views.py to render a HTTP 404 error if a question with the requested ID doesn’t exist
from django.shortcuts import get_object_or_404, render

# Import the login required decorator to prevent unaouthorised access to cetrain views.
from django.contrib.auth.decorators import login_required

# imported HttpResponseRedirect 
from django.http import HttpResponseRedirect

# imported reverse
from django.urls import reverse

# import functions from utils.py called in views
from .utils import get_json_categories, get_next_question_id, get_category_names, category_objects

# import all models
from . import models

# import apps to dynamically fetch a model in detail() & selection() view
from django.apps import apps

# import ast safely evaluate strings containing Python literal structures e.g.strings, lists, dicts
# use to convert str into list
import ast 

#######################################################################################
#######################################################################################

# Create your views here.

# define index view for home page of QuizMe project referenced in Education/urls.py
def index(request):     
    """A view for the home page of QuizMe project.

    :param request: The HTTP request object containing information about the client's request.
    :type request: HttpRequest
    :return: Return the index template
    :rtype: HttpResponse 
    """
    # if a user prematurely leaves a quiz & does not use the exit button,
    # - delete the result & session data of the current quiz 
    # - this is done for all the templates the navbar displays
    if 'quiz_result' in request.session:
        del request.session['quiz_result']
        
    # Render your template and map a URL to it
    return render(request, "index.html")

# display the category of the education quiz
# https://www.youtube.com/watch?v=sgEhb50YSTE
# get json response¹ for trivia categories from open trivia db
# index category from the dictionary id
def index_edu(request):
    """A view for the home page of education quizzes.

    :param request: The HTTP request object containing information about the client's request.
    :type request: HttpRequest
    :return: Return the edu_quiz template
    :rtype: HttpResponse
    """
    # if a user prematurely leaves a quiz & does not use the exit button,
    # - delete the result & session data of the current quiz 
    # - this is done for all the templates the navbar displays
    if 'quiz_result' in request.session:
        del request.session['quiz_result']

    # call the categories function & save its response in an assigned variable - NameError if you don't assign it
    response = get_json_categories()
            
    # call the function to return the chosen categories to present a quiz for on the homepage
    category_names = get_category_names(response)       

    # iterate over the list of category_names to return the context for each subcategory in Education app
    for category_name in category_names:
        # call the function to retrieve the objects from the django database - viewable on admin site
        question_selection =  category_objects(request, category_name)                   

        # retrieve question_selection_pks from the session (from utils.category_objects)
        # because the 1st pk needs to be indexed for the 1st question rendered
        # question_selection.first().id chose the 1st question numerically in the database, not the 1st from the randomised list
        question_selection_pks = request.session['question_selection_ids']                
    
        # the response is the dictionary for trivia categories
        # pass all the context variables into a single dictionary to render in the template correctly
        context = {'category_names': category_names,                             
                   'question_selection': question_selection,
                   'first_question_id': question_selection_pks[0]
                   }            
        
        # render the context to the homepage of education
        return render(request, 'edu_quiz/edu_quiz.html', context) 

# add a login decorator because an Education quiz requires a registered user
# write a view for the quiz question, incl the argument question_id
# question_id is the specific identifier passed in the URL when accessing this view
# it uniquely identifies and retrieves the specific question to display
# Django automatically adds an id field as the primary key for each model (i.e. question.id)
# display the question text 
# render an HTTP 404 error if a question with the requested ID doesn’t exist
@login_required(login_url='user_auth:login')
def detail(request, category_name, question_id): 
    """A view that displays the quiz question.

    :param request: The HTTP request object containing information about the client's request.
    :type request: HttpRequest
    :param category_name: The name of the category the user selected on the category homepage.
    :type category_name: str
    :param question_id: The pk of the question object
    :type question_id: int
    :return: Return the edu_detail template. 
    :rtype: HttpResponse
    """
    response = get_json_categories()
    category_names = get_category_names(response)          

    # Initialise model with a default value because the conditional checking for model gave 
    # - UnboundLocalError: local variable 'model' referenced before assignment
    model = None  

    # check if the category_name is in the list of category_names then locate its model       
    if category_name in category_names:            
        # use the category_name selected on edu_quiz.html to determine the model to get questions from
        # replace spaces and '&' in the event category names have spaces to create a valid model name
        model_name = category_name.replace(" ", "_").replace("&", "and")
        
        # use a try-except block to dynamically find a model that matches the category name
        # - dynamically:instead of explicitly specifying a fixed model in the code, 
        # - generate or determine the model to use at runtime based on certain conditions/data        
        # use apps module to access the get_model function & find the model name         
        try:            
            model = apps.get_model('Education', model_name)                        

        # render the detail template displaying the error when a model for a category_name cannot be located
        except LookupError as e:
            error_message = f"{e}"
            context = {'question': None,
                        'choices':None,
                        'category_name': category_name,
                        'error': error_message,
                        'model_exists': False  # Flag indicating whether a model exists for the template to prevent selection() exec
                        }
            print(f"context:{context}")
            return render(request, 'edu_quiz/edu_detail.html', context)
        
    # check that a model was found
    if model != None:            
        # get the question object associated with a specific question_id in the database
        question = get_object_or_404(model, pk=question_id)    
        
        # use the helper function literal_eval of the ast module to convert the str representation of the choices list
        # - in the textfield of the category model into a list
        # https://python.readthedocs.io/en/latest/library/ast.html#ast.literal_eval
        # note:ast.literal_eval is safer than eval. it only evaluates literals & not arbitrary expressions², 
        # - reducing the risk of code injection
        # use in template to iterate over the list of choices dictionaries and access the values for the 'choice' key
        convert_choices_textfield_into_list = ast.literal_eval(question.choices)            

        # render the edu_detail template & pass the 10 questions, their ids & category as context 
        context = {'question': question,
                    'choices':convert_choices_textfield_into_list,
                    'category_name': category_name,
                    'error': None,
                    'model_exists': True # Flag indicating a model exists so selection() can exec 
                    }
        
        return render(request, 'edu_quiz/edu_detail.html', context)                

# create a view that displays the quiz result 
# add a login decorator because an Education quiz requires a registered user
@login_required(login_url='user_auth:login')
def results(request, category_name): 
    """A view that displays the quiz result.

    :param request: The HTTP request object containing information about the client's request.
    :type request: HttpRequest
    :param category_name: The name of the category the user selected on the category homepage.
    :type category_name: str
    :return: Return the edu_result template. 
    :rtype: HttpResponse
    """
    # get the quiz result for the session
    result = request.session.get('quiz_result')
           
    # render the result template  
    # pass the quiz result for the session as a context variable
    context = {'result':result,
               'category_name': category_name
               }   
    return render(request, 'edu_quiz/edu_result.html', context)

# write a view to answer a question, incl the argument category_name & question_id
# it handles the submitted data
def selection(request, category_name, question_id):  
    """A a selection view that handles the submission of form data, goes to the next question and redirects to the results view. 
    Otherwise the form will be redisplayed.

    :param request: The HTTP request object containing information about the client's request.
    :type request: HttpRequest

Education/templates/index.html
{% load static %}
<!-- Home page !-->
<!-- Base template for all templates !-->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">        
        <title>{% block title %}QuizMe{% endblock %}</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">  
        <!-- must link popper before Bootstrap CSS ¹ to use tooltips on detail.html
        https://getbootstrap.com/docs/5.0/getting-started/introduction/#separate-->        
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <!--Note: link to use icons must be in base template to work in child templates)-->	
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <!--link css in base template to make it available in child templates for all 3 apps-->
        <!--NOTE:internal CSS from parent/base template is used in child template that extends it;-->
        <!--NOTE: the url to stylesheet & palcement of '/'; this renders external css correctly-->
        <link href="{% static 'CSS/StyleSheet_edu.css' %}" rel = "stylesheet" type = "text/css">                
    </head>

    <body style="background: floralwhite;">            
        
        <!-- set a black navbar 
        https://getbootstrap.com/docs/5.0/components/navbar/-->        
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-2 px-4">
            <!-- link to QuizMe home page -->
            <a class="navbar-brand me-4" href="{% url 'Education:index' %}" alt="QuizMe">
                <img src="{% static 'assets/QuizMe.jpg' %}" height="70" width="70" style="border-radius: 37%;">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <!-- create a collapsible navigation menu for smaller screens -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent" >
                <!-- list the items on the navbar -->
              <ul class="navbar-nav mr-auto py-auto" >
                
                <li class="nav-item active px-2 py-2">
                  <a class="nav-link" href="{% url 'General_Knowledge:index_gen' %}" style="color: rgb(255, 255, 255);">General Knowledge</a>
                </li>
                <li class="nav-item active px-2 py-2">
                    <a class="nav-link" href="{% url 'Education:index_edu' %}" style="color: rgb(255, 255, 255);">Education</a>
                </li>
                <li class="nav-item active px-2 py-2">
                    <a class="nav-link pe-5" href="{% url 'Entertainment:index_en' %}" style="color: rgb(255, 255, 255);">Entertainment</a>
                </li>
                <div class="d-flex align-items-center justify-content-end" style="padding-left: 165pt;">
                    <li class="nav-item ps-6 px-4 ms-4" style="color: coral;"> 
                        <!-- show a logged in user -->
                        <!-- https://stackoverflow.com/questions/57405870/how-to-display-username-at-login-link-in-navbar-after-user-has-logged-in¹ -->
                        {% if user.is_authenticated %}
                            {{user.username}}
                        {% endif %}
                    </li>
                    <li class="nav-item dropdown me-4">
                        <div class="dropdown text-right">
                            <button class="dropbtn">Account
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="dropdown-content">
                                {% if user.is_authenticated %}
                                    <a href="{% url 'user_auth:logout' %}">Logout</a>
                                {% else %}
                                    <a href="{% url 'user_auth:login' %}">Login</a>
                                    <a href="{% url 'user_auth:register' %}">Register</a>                                                                  
                                {% endif %}
                            </div>
                        </div>
                    </li>
                
                    </ul>
                    <div class="d-flex">
                        <form class="form-inline my-2 my-lg-0 me-2">
                            <input class="form-control mr-sm-2 me-2" type="search" placeholder="Find a quiz" aria-label="Search">
                            <!-- You can add additional styling or classes for further customization -->
                        </form>
                        <button class="btn my-2 my-sm-0" type="submit" id="searchbar_button" >Search</button>
                    </div>
                    
                </div>
            </div>
        </nav>
        
        {% block content %}        
        <!-- Introduction paragraph -->           
            <div class="row" style="padding-top: 25pt;">
                <div class="col-md-12"  style="text-align: center;">
                    <h1><b>Welcome to QuizMe</b></h1>
                </div> 
            </div>    

            <div class="container"  style="text-align: center;">    
                <p id=index_p style="font-family: sans-serif">QuizMe is the ultimate quiz app for curious minds! 

                    QuizMe is a fun and easy way to test your knowledge 
                     
                    on various topics, from Education, Entertainment and General Knowledge.
                   
                    You can choose from hundreds  
                   
                    of quizzes
                    
                    QuizMe is more than just a game. It's a learning tool that helps you discover new facts and improve 
                    
                     your skills. Whether you want to brush up on your trivia, prepare for an exam, or just have some fun, 
                  
                     QuizMe has something for you. 
                    </p>
                    {% if user.is_authenticated %}
                    
                        {% else %} 
                            <p id=index_p>So what are you waiting for? <a href="{% url 'user_auth:register' %}" style="color: coral;">Register</a> on QuizMe today and start quizzing!</p>         
                    {% endif %}         
            </div>

        
                <div class="col-md-12"  style="text-align: center;">
                    <h1 id="Quiz">Quiz Categories</h1>
                </div>
                <!-- The slideshow -->
                <!-- https://codeconvey.com/Tutorials/automatic-image-slider-in-html-css/ -->
                <input id="sliderSwitch" class="slider__switch" type="checkbox" name="sliderSwitch" hidden />
                    
                <div class="slider">
                    <ul class="slider__list">
                      <li class="slider__slide"><a href="{% url 'General_Knowledge:index_gen' %}"><img src="{% static 'assets/General.jpg' %}" alt="Slide image number 1" width="650" height="420"/></a></li>
                      <li class="slider__slide"><a href="{% url 'Education:index_edu' %}"><img src="{% static 'assets/Education.jpg' %}" alt="Slide image number 2 " width="650" height="420"/></a></li>
                      <li class="slider__slide"><a href="{% url 'Entertainment:index_en' %}"><img src="{% static 'assets/Entertainment.jpg' %}" alt="Slide image number 3" width="650" height="420"/></a></li>
                        
                    </ul>
                  </div>
                  <!-- slideshow button -->
                  <div class="slider__control">
                    <label for="sliderSwitch"></label>
                  </div>

                  <br>

                  <div class="col-md-12"  style="text-align: center;">
                    <h5>Select one of the images above to view it's quiz.</h5>
                </div>    

                <br>
                <!-- About Us paragraph -->
                <div class="container"  style="text-align: center;">    
                    <h1>About Us</h1>
                    <p id=index_p  style="font-family: sans-serif">In a world where traditional media is making way for digital experiences,
                    
                       we recognize the need for a platform that caters to the growing demand for 
                       
                       quizzes in education, entertainment, and general knowledge.QuizMe is here to fill 
                  
                        that void, offering a diverse range of quizzes designed to challenge, entertain, and enlighten.
                    </p>
                
                    <br>
                    <!-- Our Mission paragraph -->
                    <h1>Our Mission</h1>
                      <p id=index_p  style="font-family: sans-serif">At QuizMe, we aim to provide quiz masters with a user-friendly interface to define quizzes,
                       
                         ensuring seamless conversion between graphical representation and human-readable data formats.
                        
                          Whether you're an educator, an enthusiast, or just someone looking for a mental workout,
                       
                           our platform is designed to meet your needs. 
                      </p>
                  </div>    

                  <br>
                  <!-- Quiz categories link -->
                <div class="col-md-12"  style="text-align: center;">
                    <h4>Find all our quiz categories 
                        <a href="#Quiz" style="color: coral;">
                        here
                        </a>
                    </h4>
                </div>
            </div>  

            <br>
            
        {% endblock %}                

        <!--Copyright information-->
        <br>        
        <div class="footer" style="color: rgb(0, 0, 0);" style="text-align: center;">
            <div style="text-align: center;">
                <h7>Authors : Deandre' Wright,  Kisha Cairncross<br> &copy;copy right reserved <br></h7>
            </div>
        </div> 
        <br>    
        
        <!--Enable tooltips everywhere-->                                                                                        
        <script>
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
              return new bootstrap.Tooltip(tooltipTriggerEl)
            })
        </script>

    </body>
</html>