General_Knowledge/urls.py
# create urls.py in the directory of the education app

# import path to map a URL to a specific view function in Django
# import include to use other URL patterns from other modules (apps)
from django.urls import path, include

# import views which contain the functions or classes responsible for handling HTTP requests
# and returning appropriate responses, rendering web pages.
from . import views

#############################################################################################
#############################################################################################

# add an app_name to set the application namespace
app_name = 'General_Knowledge'

# under urlpatterns, paste the code that references the functions in views.py
urlpatterns = [
    # set a path for the home view of General Knowledge
    path('General_Knowledge/', views.index_gen, name='index_gen'),   
    # set a path for the detail view
    path('<str:category_name>/<int:question_id>/detail/', views.detail, name='gen_detail'),
    # set a path for the selection view
    path('<str:category_name>/<int:question_id>/selection/', views.selection, name='selection'),    
    # set a path for the results view
    path('<str:category_name>results/', views.results, name='results'),
    # set a path for the start a new quiz view
    path('General_Knowledge/try_new_quiz/', views.try_new_quiz, name='try_new_quiz')    
]

QuizMe/urls.py
# import admin to make the Django admin functionality available for use in your Django project
# admin allows administrators to easily add, edit, and delete records from the database
from django.contrib import admin

# import path function to define a URL pattern for the paths to apps 
# alter import to add 'include' to include additional URL patterns within the modules(apps)
from django.urls import path, include

#############################################################################################
#############################################################################################

'''
Add paths for the modules in QuizMe.
'''
# add path for admin
# add paths for the apps created in QuizMe
# edu has index.html so leave path open for it to render when server starts
urlpatterns = [
    path('admin/', admin.site.urls),      
    path('', include("Education.urls")),
    path('user_auth/', include("user_auth.urls")),
    path('Entertainment/', include("Entertainment.urls")),
    path('General_Knowledge/', include("General_Knowledge.urls"))
]

user_auth/urls.py
"""
This file contains the URL patterns for the user authentication app.
"""
from django.urls import path
from user_auth import views

app_name = 'user_auth'
urlpatterns = [
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.user_register, name="register"),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('authenticate_user/show_user', views.show_user, name='show_user'),  # The url path to user page.

]

General_Knowledge/models.py
from django.db import models

###################################################################################
###################################################################################

# Create your models here.

'''
Create a model for the quiz categories in QuizMe.
'''
# define a model for categories in the QuizMe project
class Categories(models.Model):
    # define a field to store the category name as text
    # define a field to store the description of the category as text
    category = models.TextField()
    description = models.TextField()

    # define a method to represent the model instance as a string
    # return the category name
    def __str__(self):
        """A human-readable string representation of the category object.

        :return: Return the category object
        :rtype: str
        """
        return self.category
        
'''
Create a model for the quiz subcategories in General Knowledge.
'''
# define a model for subcategories in the General Knowledge app
class Subcategories(models.Model): 
    # use database foreign keys to indicate relationships between categories and subcategories
    # - a ForeignKey field to show this many-to-one relationship
    # set a default category to 'General Knowledge' 
    # https://docs.djangoproject.com/en/3.2/topics/db/models/#many-to-one-relationships
    # https://dnmtechs.com/setting-default-value-for-foreign-key-attribute-in-django/
    # ‘on_delete’ parameter allows one to define the behaviour when the referenced object is deleted, 
    # - providing further control over the default value
    # https://docs.djangoproject.com/en/3.2/ref/models/fields/#default
    # - according to doc, for fields like ForeignKey that map to model instances, 
    # - defaults should be the value of the field they reference (pk unless to_field is set) instead of model instances
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, default='General Knowledge')

    # define a field to store the subcategory name as text
    subcategory = models.TextField()

    # define a field to store the description of the subcategory as text
    description = models.TextField()

    # define a method to represent the model instance as a string
    # return the subcategory name 
    def __str__(self):
        """A human-readable string representation of the subcategory object.

        :return: Return the subcategory object
        :rtype: str
        """
        return self.subcategory

'''
Create a General Knowledge model for the subcategory in the education quiz.
'''
# use Django's built-in object-relational mapping (ORM) & define the relevant classes
# -each entry in a SQL table represents a single object, this can be converted to a class instance in Python.  
# create a General Knowledge class that inherits from django.db.models.Model
class General_Knowledge(models.Model):      
    # use database foreign keys to indicate relationships between General Knowledge and categories        
    # - a ForeignKey field to show this many-to-one relationship
    # set a default category to General Knowledge
    # ‘on_delete’ parameter allows one to define the behaviour when the referenced object is deleted, 
    # - with cascade all related objects will also be deleted. This is useful for maintaining referential integrity in the database    
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, default='General Knowledge')       

    # set variables that represent question, choices & correct_answer in the quiz
    # use TextField to store the questions
    question = models.TextField()    
    
    # use TextField to store the list of choices 
    # set default as an empty list and allow it to be blank.
    choices = models.TextField(default = list, blank = True)

    # use TextField to store the correct answer
    correct_answer = models.TextField()

    # define a __str__ method for human-readable output
    # return question
    def __str__(self):
        """A human-readable string representation of the General Knowledge question object in a quiz.

        :return: Return the question object
        :rtype: str
        """
        return self.question        

General_Knowledge/views.py
# import render to render an HTML template with a given context and return an HttpResponse object
# use get_object_or_404 in views.py to render a HTTP 404 error if a question with the requested ID doesn’t exist
from django.shortcuts import get_object_or_404, render

# imported HttpResponseRedirect 
from django.http import HttpResponseRedirect

# imported reverse
from django.urls import reverse

# import functions from utils.py called in views
from .utils import get_json_categories, get_next_question_id, get_category_names, category_objects

# import all models
from .models import *

# import ast safely evaluate strings containing Python literal structures e.g.strings, lists, dicts
# use to convert str into list
import ast 

# import apps to dynamically fetch a model in detail() & selection() view
from django.apps import apps

#######################################################################################
#######################################################################################

# Create your views here.

# display the category of the General Knowledge quiz
# https://www.youtube.com/watch?v=sgEhb50YSTE
# get json reponse for trivia categories from open trivia db
# index category from the dictionary id
def index_gen(request):
    """A view for the home page of the General Knowledge quiz.

    :param request: The HTTP request object containing information about the client's request.
    :type request: HttpRequest
    :return: Return the gen_quiz template
    :rtype: HttpResponse
    """
    # if a user prematurely leaves a quiz & does not use the exit button,
    # - delete the result & session data of the current quiz 
    # - this is done for all the templates the navbar displays
    if 'quiz_result' in request.session:
        del request.session['quiz_result']
        
    # call the categories function & save its response in an assigned variable - NameError if you don't assign it
    response = get_json_categories()
            
    # call the function to return the chosen categories to present a quiz for on the homepage
    category_names = get_category_names(response)       

    # iterate over the list of category_names to return the context for each subcategory in General_Knowledge app
    for category_name in category_names:
        # call the function to retrieve the objects from the django database - viewable on admin site
        question_selection =  category_objects(request, category_name)           
        
        # retrieve question_selection_pks from the session (from utils.category_objects)
        # because the 1st pk needs to be indexed for the 1st question rendered
        # question_selection.first().id chose the 1st question numerically in the database, not the 1st from the randomised list
        question_selection_pks = request.session['question_selection_ids']        
        print(f"index_gen=question_selection_ids in session:{question_selection_pks}") ##     
    
        # the response is the dictionary for trivia categories
        # pass all the context variables into a single dictionary to render in the template correctly
        context = {'category_names': category_names,                                  
                   'question_selection': question_selection,
                   'first_question_id': question_selection_pks[0]
                   }            
        print(f"context:{context}") ##
        
        # render the context to the homepage of General_Knowledge
        return render(request, 'gen_quiz/gen_quiz.html', context) 

# write a view for the quiz question, incl the argument question_id
# question_id is the specific identifier passed in the URL when accessing this view
# it uniquely identifies and retrieves the specific question to display
# Django automatically adds an id field as the primary key for each model (i.e. question.id)
# display the question text 
# render an HTTP 404 error if a question with the requested ID doesn’t exist
def detail(request, category_name, question_id):  
    """A view that displays the quiz question.

    :param request: The HTTP request object containing information about the client's request.
    :type request: HttpRequest
    :param category_name: The name of the category the user selected on the category homepage.
    :type category_name: str
    :param question_id: The pk of the question object
    :type question_id: int
    :return: Return the gen_detail template. 
    :rtype: HttpResponse
    """
    response = get_json_categories()
    category_names = get_category_names(response)  

    # Initialise model with a default value because the conditional checking for model gave 
    # - UnboundLocalError: local variable 'model' referenced before assignment
    model = None

    # check if the category_name is in the list of category_names then locate its model    
    if category_name in category_names:
        # use the category_name selected on gen_quiz.html to determine the model to get questions from
        # replace spaces and '&' in the event category names have spaces to create a valid model name
        model_name = category_name.replace(" ", "_").replace("&", "and")
        print(f"Model Name: {model_name}") ##

        # use a try-except block to dynamically find a model that matches the category name
        # - dynamically:instead of explicitly specifying a fixed model in the code, 
        # - generate or determine the model to use at runtime based on certain conditions/data        
        # use apps module to access the get_model function & find the model name         
        try:            
            model = apps.get_model('General_Knowledge', model_name)                        

        # render the detail template displaying the error when a model for a category_name cannot be located
        except LookupError as e:
            error_message = f"{e}"
            context = {'question': None,
                        'choices':None,
                        'category_name': category_name,
                        'error': error_message,
                        'model_exists': False  # Flag indicating whether a model exists for the template to prevent selection() exec
                        }
            print(f"context:{context}")
            return render(request, 'gen_quiz/gen_detail.html', context)    
    
    # check that a model was found
    if model != None: 
        # get the question object associated with a specific question_id in the database
        question = get_object_or_404(model, pk=question_id)    
        print(f"\n\nquestion:{question}")
        print(f"correct_answer:{question.correct_answer}")
    
        # use the helper function literal_eval of the ast module to convert the str representation of the choices list
        # - in the textfield of the category model into a list
        # https://python.readthedocs.io/en/latest/library/ast.html#ast.literal_eval
        # note:ast.literal_eval is safer than eval. it only evaluates literals & not arbitrary expressions, 
        # - reducing the risk of code injection
        # use in template to iterate over the list of choices dictionaries and access the values for the 'choice' key
        convert_choices_textfield_into_list = ast.literal_eval(question.choices)    
    
        # render the gen_detail template & pass the 10 questions, their ids & category as context 
        context = {'question': question,
                   'choices':convert_choices_textfield_into_list,
                   'category_name': category_name 
                   }
        print(f"context:{context}") ##

        # render the context to the detail template of General_Knowledge
        return render(request, 'gen_quiz/gen_detail.html', context)

# create a view that displays the quiz result 
def results(request, category_name): 
    """A view that displays the quiz result.

    :param request: The HTTP request object containing information about the client's request.
    :type request: HttpRequest
    :param category_name: The name of the category the user selected on the category homepage.
    :type category_name: str
    :return: Return the gen_result template. 
    :rtype: HttpResponse
    """
    # get the quiz result for the session
    result = request.session.get('quiz_result')
           
    # render the result template  
    # pass the quiz result for the session as a context variable
    context = {'result':result,
               'category_name': category_name
               }   
    
    # render the context to the result template of General_Knowledge
    return render(request, 'gen_quiz/gen_result.html', context)

'''
Write a selection view that handles the submission of form data, goes to the next question and redirects to the results view."
'''
# write a view to answer a question, incl the argument category_name & question_id
# it handles the submitted data
def selection(request, category_name, question_id):   
    """A a selection view that handles the submission of form data, goes to the next question and redirects to the results view. 
    Otherwise the form will be redisplayed.

    :param request: The HTTP request object containing information about the client's request.
    :type request: HttpRequest
    :param category_name: The name of the category the user selected on the category homepage.
    :type category_name: str
    :param question_id: The pk of the question object the user has submitted
    :type question_id: int
    :return: Return the gen_detail or the gen_result template. 
    :rtype: HttpResponse
    """  
    # pk refers to the primary key field of a database table
    # django automatically creates a primary key for each model
    response = get_json_categories()
    category_names = get_category_names(response)

    # Initialise model with a default value because the conditional checking for model gave 
    # - UnboundLocalError: local variable 'model' referenced before assignment

General_Knowledge/templates/gen_quiz/gen_detail.html
{% extends "index.html" %}
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
    	integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">		
    	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    	<!--NOTE: the url to stylesheet & palcement of '/'; this renders external css correctly-->
    	<link href="{% static 'CSS/StyleSheet_edu.css' %}" rel = "stylesheet" type = "text/css"> 
    	<meta charset="utf-8" />
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}General Knowledge Detail{% endblock %}</title>	    
    </head>    

    <body>
    	{% block content %}     
    	    <section>
                <div class= row>                    
                    <div class= "col-md-6 d-flex justify-content-center pt-3 pe-10 me-0 mb-6">
                        <!-- use tooltips to display a message when hovering over the exit button for a quiz
                         https://getbootstrap.com/docs/5.0/components/tooltips/#examples-->
                        <a class="btn btn-outline-light" 
                        id="gen_detail_btn" style="font-size: larger;"
                        href="{% url 'General_Knowledge:try_new_quiz' %}"
                        data-bs-toggle="tooltip" data-bs-placement="right" 
                        title="Warning: Leaving the quiz will cause you to lose the data submitted.">
                            Exit
                        </a>
                    </div>
                </div>

                <div class="container-fluid text-center">
                    <div class="row my-0 align-items-center justify-content-center">			
                        <div class = "col d-flex justify-content-center">
                            <div class="card gen_p" style="width: 40rem;">		
                                <div class="card-body" id="no-underline">
                                    <!--add a margin below the card-title -->
                                    <h1 class="card-title mb-4"><i>{{ category_name }} quiz!</i></h1>		

                                        <!--show a form for each question in the quiz -->
                                        <!--the post method was used to send data to the server-->
                                        <!--the url in the action attribute was used to send data to the server-->
                                        <form action="{% url 'General_Knowledge:selection' category_name=category_name question_id=question.id %}" method="POST">
                                            <!--add the csrf_token to all post forms targeted at internal urls to protect against Cross Site Forgery-->
                                            {% csrf_token %}

                                            <!--The template system uses dot-lookup syntax to access variable attributes.-->
                                            <!-- Django does a dictionary lookup on the object question.-->
                                            <!--Failing that, it tries an attribute lookup – which works, in this case. -->
                                            <!--If attribute lookup has failed, it would’ve tried a list-index lookup.-->
                                            <!--check if there are question objects passed as context-->                    
                                            {% if question %}
                                        
                                                    <!--display the question text by accessing its question attribute -->
                                                    <!--add a margin below the question -->
                                                    <h3 class="mb-4"> {{ question.question }} </h3> 

                                                    <!--display error message if user did not select a choice before submitting-->
                                                    {% if error_message %}
    	    							                <p><strong>{{error_message}}</strong></p>
    	    							            {% endif %}

                                                    <!--group related elements in a form with fieldset-->
                                                    <fieldset>                                                 
                                                        <!--iterate over the choices attribute to add a radio button for each choice
                                                         associated with a specific question in the database-->
                                                        {% for choice in choices %}
                                                            <!--Radio buttons. Each choice that is associated with that particular question is
                                                            then displayed using a radio button in a form.-->
                                                            <!--The name of each radio button is choice-->
                                                            <!--selected value for each question will be sent to the server-->  
                                                            <!-- uniquely identify the radio button within the form-->
                                                            <!--the value attribute is the identifier for the user's choice associated with the question-->                                                                                              
                                                            <input type="radio" name="choice" 
                                                            id="choice{{forloop.counter}}" value="{{ choice.id }}" />                        
                                                            <!-- access the value associated with the 'choice' key in the question.choices dictionary-->
                                                            <label for="choice{{ forloop.counter }}">
                                                                {{ choice.choice }} 
                                                            </label>                                                                                                                                                                                                
                                                            <br/><br/>
                                                        {% endfor %}                                                                                                                                                                            
                                                        
                                                        <!-- a button that allows the user to submit their choice-->
                                                        <!--when a user selects one of the radio buttons and submits the form,
                                                             it’ll POST the data “choice=id” where id is the ID of the selected choice-->                                                
                                                        <input type="Submit" value="Save" class="btn btn-outline-light" id="gen_detail_btn"/>                                                                                                
                                                    </fieldset>    

                                            <!--display error message if there are no questions-->                                                                                        
                                            {% else %}
                                                <p><strong>{{ error_message }}</strong></p>
                                            {% endif %}
                                                
                                        </form>                                                                
                                    
                                </div>	
                            </div>	
                        </div>
                    </div>	                
                </div>
            </section>
    	{% endblock %}
    </body>
</html>

General_Knowledge/templates/gen_quiz/gen_result.html
{% extends "index.html" %}
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
    	integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">		
    	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    	<!--NOTE: the url to stylesheet & palcement of '/'; this renders external css correctly-->
    	<link href="{% static 'CSS/StyleSheet_edu.css' %}" rel = "stylesheet" type = "text/css"> 
    	<meta charset="utf-8" />
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}General Knowledge Result{% endblock %}</title>	
    </head>    
    
    <body>
    	{% block content %}              
    	    <section>
                <div class="container-fluid text-center">
                    <div class="row my-5 align-items-center justify-content-center">
                        <div class = "col d-flex justify-content-center">
                            <p style="width: 40rem;" class="gen_p">
                                <i>Your result for the {{ category_name }} Quiz </i>
                                <br>
                            
                                <!-- show score-->
                                {% if result %}
                                    {{result}} / 10 
                            
                                <!-- display an error message if score is unavailable-->
                                {% else %}
                                    <p>
                                        <b>No score calculated</b>
                                    </p>
                                
                                {% endif %}
                                <br>
                                
                                <!-- enter a view url here to start a new General_Knowledge quiz -->
                                <a style="color: coral;" href="{% url 'General_Knowledge:try_new_quiz' %}">
                                    Try again?
                                </a>
                                <br><br>
                            
                                <!-- enter a view url here to register as a new user -->
                                Or sign up
                                <a style="color: coral;" href="{% url 'user_auth:register' %}">
                                    here
                                </a>
                                to access all quizzes                                                                        
                            </p>
                        </div>
                    </div>
                </div>
            </section>
    	{% endblock %}
    </body>
</html>